settings:
  show_progress: true
  debug: false
  log_dir: LOG
  report_dir: REPORT

fxos:
  username: admin
  password: Admin123
  devices:
    HX00-FXOS-01: https://10.10.88.246/
    HX00-FXOS-02: https://10.10.88.245/
    HX00-FXOS-BK: https://10.10.88.243/
    HX01-FXOS-01: https://10.6.88.246/
    HX01-FXOS-02: https://10.6.88.245/
    HX01-FXOS-BK: https://10.6.88.243/
    HX02-FXOS-01: https://10.12.88.213/
    HX02-FXOS-02: https://10.12.88.215/
    HX02-FXOS-BK: https://10.12.88.243/
    HX03-FXOS-01: https://10.13.88.247/
    HX03-FXOS-02: https://10.13.88.246/
    HX03-FXOS-BK: https://10.13.88.241/
    HX04-FXOS-01: https://10.62.88.245/
    HX04-FXOS-02: https://10.62.88.244/
    HX04-FXOS-BK: https://10.62.88.242/
    HX05-FXOS-01: https://10.65.88.245/
    HX05-FXOS-02: https://10.65.88.244/
    HX05-FXOS-BK: https://10.65.88.212/
    HX06-FXOS-01: https://10.66.88.211/
    HX06-FXOS-02: https://10.66.88.213/
    HX06-FXOS-BK: https://10.66.88.221/
fortigate:
  username: admin
  password: Admin@13579
  port: 22
  hosts:
  - 10.10.88.247
  - 10.6.88.247
  - 10.12.88.251
  - 10.13.88.251
  - 10.62.88.251
  - 10.65.88.251
  - 10.66.88.251
  thresholds:
    cpu_percent:
      warn: 50
      crit: 80
    mem_percent:
      warn: 50
      crit: 80
    disk_percent:
      warn: 60
      crit: 80
    uptime_days:
      min: 3
oxidized:
  base_urls:
  - http://10.10.80.11:8888/nodes
  - http://10.10.80.12:8888/nodes
  - http://10.10.80.13:8888/nodes
  - http://10.10.80.14:8888/nodes
servers:
  port: 22
  thresholds:
    disk_percent:
      warn: 50
      crit: 80
    mem_percent:
      LOGSTASH:
        warn: 50
        crit: 80
      ES:
        warn: 80
        crit: 90
      FLOW:
        warn: 80
        crit: 90
  logstash:
    username: root
    password: Admin@12300.
    hosts:
      HX00-LOGSTASH: 10.10.86.101
      HX01-LOGSTASH: 10.6.86.32
      HX02-LOGSTASH: 10.10.86.111
      HX03-LOGSTASH: 10.10.86.116
      HX04-LOGSTASH: 10.62.86.2
      HX05-LOGSTASH: 10.6.86.52
      HX06-LOGSTASH: 10.6.86.62
  es:
    username: root
    password: Admin@12300.
    hosts:
      HX00-ES: 10.10.86.100
      HX01-ES: 10.6.86.31
      HX02-ES: 10.10.86.110
      HX03-ES: 10.10.86.115
      HX04-ES: 10.62.86.1
      HX05-ES: 10.6.86.51
      HX06-ES: 10.6.86.61
  flow:
    username: root
    password: Admin@12300.
    hosts:
      HX00-FLOW: 10.10.86.102
      HX01-FLOW: 10.6.86.33
      HX02-FLOW: 10.10.86.112
      HX03-FLOW: 10.10.86.117
      HX04-FLOW: 10.62.86.3
      HX05-FLOW: 10.6.86.53
      HX06-FLOW: 10.6.86.63
  flow_checks:
    require_ports:
    - 5601
    - 9200
    - 9300
    require_containers:
    - opt-kibana-1
    - elastiflow-logstash
    - opt-elasticsearch-1
    index_prefix: elastiflow-4.0.1-
    index_size_limit_bytes: 1073741824
    segment_max_non_recent: 3
esn9k:
  ignore_alarm_file: YAML/Ignore_alarm.yaml
  kibana_bases:
    HX00-ES: http://10.10.86.100:5601
    HX01-ES: http://10.6.86.31:5601
    HX02-ES: http://10.10.86.110:5601
    HX03-ES: http://10.10.86.115:5601
    HX04-ES: http://10.62.86.1:5601
    HX05-ES: http://10.6.86.51:5601
    HX06-ES: http://10.6.86.61:5601
  index_pattern: '*-n9k-*-*'
  time_gte: now-3d
  time_lt: now
